---
title: "SIG dengan Leaflet"
author: "Erzasyfr"
format: html
editor: visual
---

```{r, echo=FALSE}
library(sf)
library(leaflet)

```

## Peta Jawa Timur

Ini adalah peta Jawa Timur

```{r}
jatim <- st_read("D:/Semester 6/SIG/gis-biostat-fkm")

set.seed(63)
jatim$dataacak <- runif(nrow(jatim), 2, 50)

warna <- colorBin(
  palette = "Set1",
  domain = jatim$dataacak,
  bins = 5
)

#Set Leaflet
leaflet(jatim) %>%
  
#Set Peta Dasar
  addProviderTiles("Thunderforest.OpenCycleMap") %>%

#Set View Bds Long & Lat
  setView(lng = 112.76, lat = -7.25, zoom = 11) %>%
  
#Layer Tambahan
  addPolygons(fillColor = ~warna(dataacak),
              fillOpacity = 0.8,
              weight = 1,
              color = "black",
              opacity = 1
              ) %>%
  addCircles(lat = -8.174, lng = 113.687, radius = 50, popup = "Radius 50m", color = "red")  %>%
  addCircles(lat = -8.174, lng = 113.688, radius = 50, color = "blue") %>%
  addMarkers(lat = -8.174, lng = 113.688, popup = "Siloam Jember") %>%
  addMarkers(data[1:10, ], 
             lat = data[1:10, ]$lat,
             lng = data[1:10, ]$lng) %>%
  addCircles(data[1:10, ],
            lat = data[1:10, ]$lat,
            lng = data[1:10, ]$lng,
            popup = data[1:10, ]$Tabel) %>%
  
#Marker di Jember
#Latitude -8.25000000, longitude 113.65000000
  addMarkers(lat = -8.25000000, lng = 113.65000000, popup = "Kabupaten Jember")
```
